engines:
  rubocop:
    enabled: true
  csslint:
    enabled: true
    checks:
      universal-selector:
        enabled: false
      box-sizing:
        enabled: false
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
exclude_paths:
  - "**/vendor/**/*"
