engines:
  rubocop:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
exclude_paths:
  - "**/vendor/**/*"
